In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5,6])
b = np.array([7,8,9,10,11,12])
print(a)
print(b)

[1 2 3 4 5 6]
[ 7  8  9 10 11 12]


In [3]:
type(a)

numpy.ndarray

OPERATIONS & METHODS

In [4]:
print(a+b)
print(a-b)
print(a*b)

[ 8 10 12 14 16 18]
[-6 -6 -6 -6 -6 -6]
[ 7 16 27 40 55 72]


In [15]:
#creating a 2D array
a2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#creating a 3d array
a3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [8]:
print(a2.shape)
print(a3.shape)

(2, 3)
(2, 2, 3)


In [10]:
print(a3.ndim)

3


In [11]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [17]:
np.random.randint(1,21, size=(3, 4))

array([[17,  6,  1, 13],
       [ 7,  8, 16, 19],
       [15, 20,  9,  5]], dtype=int32)

In [18]:
x = np.array([[7,2,3],[3,9,4],[3,4,5]])
y = np.array([[3,4,5],[3,9,4],[7,2,3]])
print(x)
print(y)

[[7 2 3]
 [3 9 4]
 [3 4 5]]
[[3 4 5]
 [3 9 4]
 [7 2 3]]


In [19]:
print(x*y)

[[21  8 15]
 [ 9 81 16]
 [21  8 15]]


In [20]:
print(x@y) #matrix multiplication

[[ 48  52  52]
 [ 64 101  63]
 [ 56  58  46]]


In [21]:
np.dot(x,y)

array([[ 48,  52,  52],
       [ 64, 101,  63],
       [ 56,  58,  46]])

In [22]:
x.mean()

np.float64(4.444444444444445)

In [24]:
round(x.mean())

4

In [25]:
print(x.sum())
print(x.var())
print(x.std())

40
4.469135802469136
2.1140330656044943


In [26]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print(np.percentile(arr,25))  # 25th percentile
print(np.percentile(arr,50))  # 50th percentile (median)
print(np.percentile(arr,75))  # 75th percentile 

3.0
5.0
7.0
